name: Android APK (DadDash)
on:
  workflow_dispatch:
  push:
    paths:
      - "DadDash-Compose.zip"
      - ".github/workflows/android.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o DadDash-Compose.zip
          echo "PROJECT_DIR=DadDash-Compose" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DadDash-debug-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
