name: Android APK (DadDash) — Kotlin2 fix
on:
  workflow_dispatch:
  push:
    paths:
      - "DadDash-Compose.zip"
      - ".github/workflows/android.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl zip
          test -f DadDash-Compose.zip
          unzip -o DadDash-Compose.zip
          echo "PROJECT_DIR=DadDash-Compose" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Gradle 8.7 (SDKMAN)
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle -v

      # 🔧 Patch Gradle for Kotlin 2 + Compose
      - name: Apply Compose compiler plugin + remove old composeOptions
        run: |
          FILE="$PROJECT_DIR/app/build.gradle.kts"
          # add plugin
          sed -i 's/id("org.jetbrains.kotlin.android")/id("org.jetbrains.kotlin.android")\n    id("org.jetbrains.kotlin.plugin.compose")/' "$FILE"
          # remove composeOptions block (not needed with plugin)
          perl -0777 -pe 's/composeOptions\s*\{[^}]*\}//s' -i "$FILE"
          echo "Patched $FILE:"
          grep -n 'plugin.compose' -n "$FILE" || true

      - name: Build debug APK
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle --no-daemon --stacktrace assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DadDash-debug-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
